# Generated by Django 6.0.4 on 2026-04-22 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='roll_number',
        ),
    ]
