# Generated by Django 6.0.4 on 2026-04-22 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='code',
        ),
    ]
